# Generated by Django 6.0.3 on 2026-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
