# Generated by Django 6.0.3 on 2026-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_paid_amount_invoice_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ran_kilometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
