# Generated by Django 6.0.3 on 2026-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_product_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
