# Generated by Django 5.2.12 on 2026-04-03 23:18

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_product_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=billing.models.signature_upload_path),
        ),
    ]
