# Generated by Django 5.2.12 on 2026-04-06 17:57

from django.db import migrations, models


def normalize_part_numbers(apps, schema_editor):
    Product = apps.get_model('billing', 'Product')
    seen = {}

    for product in Product.objects.all().order_by('pk'):
        part_number = (product.part_number or '').strip()
        if not part_number:
            continue

        key = part_number.lower()
        if key in seen:
            seen[key] += 1
            new_part_number = f"{part_number}-{seen[key]}"
            while Product.objects.filter(part_number=new_part_number).exists():
                seen[key] += 1
                new_part_number = f"{part_number}-{seen[key]}"
            product.part_number = new_part_number
            product.save(update_fields=['part_number'])
        else:
            seen[key] = 0
            if product.part_number != part_number:
                product.part_number = part_number
                product.save(update_fields=['part_number'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_replace_paid_with_discount'),
    ]

    operations = [
        migrations.RunPython(normalize_part_numbers, noop_reverse),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
