# Generated by Django 5.2.12 on 2026-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_invoice_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
