# Generated by Django 5.2.12 on 2026-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_invoice_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='next_due_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
