# Generated by Django 5.2.12 on 2026-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_invoice_status_invoice_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]

# Made with Bob
